#!/bin/sh
set -e 

# Accept filename or pipe
[ $# -ge 1 -a -f "$1" ] && file="$1" || input="-"

RESULT=$(cat $file \
  `#-----------------------------` 				\
  `# Inline Command Processing:` 				\
  `#-----------------------------` 				\
  | sed -e "s/^#\(\s\)\(.*\)/<h1># \2<\/h1>/" `# Header 1`	\
  | sed -e "s/^##\(\s\)\(.*\)/<strong>## \2<\/strong>/" `# Header 2`  	\
  | sed -e "s/^###\(\s\)\(.*\)/<strong>### \2<\/strong>/" `# Header 3` 	\
  | sed -e "s/^---/<hr\/>/" `# Horizontal Rule`                 \
  | sed -e "s/^>\(\s\)\(.*\)/<q>\2<\/q>/" `# Quote`	 	\
  | sed -e 's/!\[\(.*\)\](\(.*\))/<img src="\2" alt="\1">/' `#Img`\
  | sed -e 's/\[\(.*\)\](\(.*\))/<a href="\2">\1<\/a>/' `#Link`	\
)

printf '<!-- generated by mdhtml.sh -->\n'
printf '<html><head>'
printf '<link rel="stylesheet" type="text/css" href="styles.css"/>'
printf '<title>Laughing Biscuit</title>'
printf '</head><body><pre>'
printf "$RESULT"
printf '</pre></body></html>'
